# --- Configuraci√≥n Global ---
global:
  postgresql:
    auth:
      postgresPassword: "supersecretpassword"
      username: "neuralbank"
      password: "neuralbank123!"
      database: "neuralbank"

# --- Backend ---
backend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-backend
    tag: "latest"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

# --- Frontend ---
frontend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-front 
    tag: "latest"
    pullPolicy: Always
  service:
    port: 80
  replicaCount: 1

# --- Proxy (Gateway Nginx) ---
proxy:
  image:
    repository: nginxinc/nginx-unprivileged
    tag: "latest"
  service:
    type: LoadBalancer
    port: 80

# --- Keycloak Configuration ---
keycloak:
  issuerUrl: 'https://rhbk.apps.cluster-wmdrk.wmdrk.sandbox2096.opentlc.com/realms/neuralbank'
  clientId: 'neuralbank'
  clientSecret: 'Uv6QyV6fa08eIhDNWTRtRdaHQjmXepAF'
  authorizationEndpoint: 'https://rhbk.apps.cluster-wmdrk.wmdrk.sandbox2096.opentlc.com/realms/neuralbank/protocol/openid-connect/auth'
  redirectUri: 'https://neuralbank.apps.cluster-wmdrk.wmdrk.sandbox2096.opentlc.com/auth/callback'
  tokenEndpoint: 'https://rhbk.apps.cluster-wmdrk.wmdrk.sandbox2096.opentlc.com/realms/neuralbank/protocol/openid-connect/token'
  postLogoutRedirectUri: 'https://neuralbank.apps.cluster-wmdrk.wmdrk.sandbox2096.opentlc.com'

# --- API Configuration ---
api:
  baseUrl: '/api'