# --- Configuraci√≥n Global ---
global:
  postgresql:
    auth:
      postgresPassword: "supersecretpassword"
      username: "neuralbank"
      password: "neuralbank123!"
      database: "neuralbank"

# --- Backend ---
backend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-backend
    tag: "latest"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

# --- Frontend ---
frontend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-front 
    tag: "pkce"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1


# --- Keycloak Configuration ---
# Domains updated by install script; clientSecret replaced by playbook after Keycloak realm is ready (client "neuralbank")
keycloak:
  issuerUrl: 'https://rhbk.apps.cluster-7cnvn.7cnvn.sandbox5547.opentlc.com'
  clientId: 'neuralbank-frontend'
  clientSecret: 'OIDC_CLIENT_SECRET_PLACEHOLDER'
  authorizationEndpoint: 'https://rhbk.apps.cluster-7cnvn.7cnvn.sandbox5547.opentlc.com'
  redirectUri: 'https://neuralbank.apps.cluster-7cnvn.7cnvn.sandbox5547.opentlc.com'
  tokenEndpoint: 'https://rhbk.apps.cluster-7cnvn.7cnvn.sandbox5547.opentlc.com'
  postLogoutRedirectUri: 'https://neuralbank.apps.cluster-7cnvn.7cnvn.sandbox5547.opentlc.com'

# --- API Configuration ---
api:
  baseUrl: '/api'