apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-pipelines-db
  namespace: workshop-pipelines
  labels:
    app: workshop-pipelines-db
    app.openshift.io/runtime: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-pipelines-db
  template:
    metadata:
      labels:
        app: workshop-pipelines-db
    spec:
      serviceAccountName: workshop-pipelines-db-sa
      securityContext:
        fsGroup: 26
        runAsUser: 26
        runAsGroup: 26
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-15:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 26
            runAsGroup: 26
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workshop-pipelines-db-secret
                  key: postgres-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: workshop-pipelines-db-secret
                  key: database
            - name: POSTGRESQL_INITDB_ARGS
              value: "--auth-host=md5 --auth-local=trust"
            - name: POSTGRESQL_PGCTLTIMEOUT
              value: "60"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: workshop-pipelines-db-secret
                  key: password
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: workshop-pipelines-db-secret
                  key: username
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: workshop-pipelines-db-pvc

