apiVersion: v1
kind: ConfigMap
metadata:
  name: my-custom-plugin
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-custom-plugin
    spec:
      version: v1.0
      generate:
        command: ["echo", "Generando manifest desde CMP..."]