apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rolebinding.yaml
  - postgres.yaml
  - keycloak-initial-admin.yaml
  - keycloak-db-secret.yaml
  - keycloak.yaml
  - keycloak-neuralbank-realm.yaml
  - keycloak-devhub-realm.yaml

namespace: rhbk-operator
