apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway.yaml
  - smcp-controlplane.yaml
  - kuadrant-ratelimit-service.yaml
  - gateway-route.yaml
  - litemaas-gateway-route.yaml
  - ratelimit-policy-litemaas-gateway.yaml

namespace: istio-system
