apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - monitoring-stack.yaml
  - servicemonitor-kuadrant.yaml
  - servicemonitor-litemaas-gateway.yaml
  - servicemonitor-neuralbank-gateway.yaml
