apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - resources/admin-permissions.yaml
  - resources/cmp-plugin-configmap.yaml
  - consolelink.yaml

patches:
  - path: patches/argocd-instance-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ArgoCD
      name: openshift-gitops