apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuralbank-db
  labels:
    app: neuralbank-db
    app.openshift.io/runtime: postgresql
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuralbank-db
  template:
    metadata:
      labels:
        app: neuralbank-db
    spec:
      serviceAccountName: neuralbank-proxy-sa
      securityContext:
        fsGroup: 26
        runAsUser: 26
        runAsGroup: 26
      initContainers:
        - name: create-database
          image: registry.redhat.io/rhel8/postgresql-13:latest
          imagePullPolicy: Always
          env:
            - name: PGPASSWORD
              value: "{{ .Values.global.postgresql.auth.postgresPassword }}"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB_NAME
              value: "{{ .Values.global.postgresql.auth.database }}"
          command: ["sh", "-c"]
          args:
            - |
              until pg_isready -h localhost -U ${POSTGRES_USER}; do
                sleep 2
              done
              psql -h localhost -U ${POSTGRES_USER} -d postgres -c "CREATE DATABASE ${POSTGRES_DB_NAME};"
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-13:latest
          imagePullPolicy: Always
          securityContext:
            runAsUser: 26
            runAsGroup: 26
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: "{{ .Values.global.postgresql.auth.postgresPassword }}"
            - name: POSTGRESQL_DATABASE
              value: "{{ .Values.global.postgresql.auth.database }}"
            - name: POSTGRESQL_INITDB_ARGS
              value: "--auth-host=md5 --auth-local=trust"
            - name: POSTGRESQL_PGCTLTIMEOUT
              value: "60"
            - name: POSTGRESQL_PASSWORD
              value: "{{ .Values.global.postgresql.auth.postgresPassword }}"
            - name: POSTGRESQL_USER
              value: "postgres"
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neuralbank-db-pvc