apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rolebinding.yaml
  #- ols-embeddings.yaml
  - lightspeed-postgres-secret.yaml
  - lightspeed-postgres.yaml
  #- lightspeed-postgres-init-job.yaml  # Deshabilitado - usando una sola base de datos
  - backstage.yaml
  - app-config.yaml
  - dynamic-plugins.yaml
  - rhdh-rbac-policy.yaml
  - llama-stack-secrets.yaml
  - llama-stack-config.yaml
  - lightspeed-secrets.yaml
  - lightspeed-stack.yaml
  - proxy.yaml

namespace: developer-hub
