apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rolebinding.yaml
  # secrets-rhdh: created by install-gitops.yaml from Keycloak when Keycloak is operational (template: secret-secrets-rhdh.yaml.j2)
  #- ols-embeddings.yaml
  # Lightspeed/llama-stack disabled (image version conflicts)
  #- lightspeed-postgres-secret.yaml
  #- lightspeed-postgres.yaml
  #- lightspeed-postgres-init-job.yaml
  - backstage.yaml
  - app-config.yaml
  - dynamic-plugins.yaml
  - rhdh-rbac-policy.yaml
  #- llama-stack-secrets.yaml
  #- llama-stack-config.yaml
  #- lightspeed-secrets.yaml
  #- lightspeed-stack.yaml

namespace: developer-hub
