channel: stable-4.20
version: 4.20.4
subscriptions:
  - name: devspaces
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
    startingCSV: devspacesoperator.v3.24.0
  - name: rhcl-operator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: servicemeshoperator3
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
