channel: stable-4.20
version: 4.20.1
subscriptions:
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  - name: devspaces
    namespace: openshift-operators
    channel: stable
    source: redhat-operators    
  - name: rhcl-operator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: servicemeshoperator3
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: kuadrant-operator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
