channel: stable-4.18
version: 4.20
subscriptions:
  - name: patch-operator
    namespace: patch-operator
    channel: stable
    source: community-operators
  - name: devspaces
    namespace: openshift-operators
    channel: stable
    source: redhat-operators    
  - name: rhcl-operator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: servicemeshoperator3
    namespace: openshift-operators
    channel: stable
    source: redhat-operators    
rhdh:
  namespace: rhdh-operator
  channel: fast
  startingCSV: rhdh-operator.v1.8.0
  enabled: true
rhbk:
  namespace: rhbk-operator
  channel: stable-v26.4
  enabled: true
gitlab:
  namespace: gitlab-system
  channel: stable
  startingCSV: gitlab-operator-kubernetes.v2.2.1
  source: community-operators
  instance:
    enabled: false
  enabled: false

acs:
  enabled: false
sealedsecrets:
  enabled: false
gitops:
  enabled: false
knative:
  enabled: false
kafka:
  enabled: false
  dedicatedNode: false
patchoperator:
  enabled: true
