# Site Settings
title: "Security Microservice with Connectivity Link using OpenID Connect (OIDC)"
description: "Zero Trust Architecture: Automate the installation with OpenShift GitOps of Connectivity Link, Service Mesh 3, Red Hat Build of Keycloak, and a full-stack application secured with Authorino (OIDC) and rate limiting on OpenShift 4.20+"
url: "https://maximilianopizarro.github.io"
baseurl: "/connectivity-link"

# Build Settings
markdown: kramdown
highlighter: rouge
# GitHub Pages supports these plugins by default
plugins:
  - jekyll-feed
  - jekyll-sitemap
# If plugins don't work, remove them and use only built-in Jekyll features

# Theme Settings
theme: null
plugins_dir: _plugins

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

